[package]
name = "chord-parser"
description = "Utilities for parsing chord signatures"
authors = ["Krazy Dev"]
repository = "https://github.com/RealKrazy/chord-parser/"
license = "MIT"
version = "1.1.1"
edition = "2021"

[dependencies]
